export default function Home() {
    return (
        <div>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
            <h1>Welcome to Dream Ahead</h1>
        </div>
    );
}
